### ISSUE TITLE
FITS Projections

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/bullseye#61]
@o-smirnov I've noticed the SIN projection doesn't do very well at higher declinations (this is actually what causes the facets to overlap when you stitch them together. It will be even worse when you start doing w-projected images and it is giving me some headaches comparing these two...

When you create these facets and drag them into tigger you can actually see the overlap very clearly. Not sure what projection you are using in tigger? Is there any other coordinate system that is better suited for larger images at any declination? 

One way around this is to make the coordinates in the facets relative to ra=0,dec=0 in the centre facet, stitch them together and then set the centre pixel coordinate. At least that way the w-projected image and the stitched faceted image have the same wrong coordinates at higher declination, but I feel this is very hacky and there ought to be a better solution?

**Comment by bmerry** [comment]
@bennahugo what type of faceting are you doing i.e. do all the facets lie in a single plane, or is each facet tangent to the celestial sphere as its centre?

**Comment by o-smirnov** [comment]
I'm surprised -- I thought SIN projection was supposed to behave the same way regardless of declination.  Isn't SIN just an orthogonal projection onto the tangent plane, or am I missing something?

**Comment by bmerry** [comment]
> I'm surprised -- I thought SIN projection was supposed to behave the same way regardless of declination.

That's also my understanding of the FITS format: distortion depends on distance away from the reference value, and shouldn't depend on declination.

**Comment by bennahugo** [comment]
Hmm... I agree that there should be increasing distortion further from field centre. Something must be off with my coordinate generation if it is not the SIN coordinates.

**Comment by o-smirnov** [comment]
This to FITS coordinate systems is like the mountain was to Moses: http://fits.gsfc.nasa.gov/fits_wcs.html

**Comment by bmerry** [comment]
@bennahugo, if you're in the SKA offices at some point I can work through this with you. I spent a lot of time reading the WCS specs to figure out how to correctly set up the keywords in my output files, so I'm reasonably familiar with it.

**Comment by bennahugo** [comment]
@bmerry @o-smirnov Thanks I will take a look and come in from tomorrow
